// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPermisos.Data;

#nullable disable

namespace SistemaPermisos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250320031541_ActualizacionTodo")]
    partial class ActualizacionTodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPermisos.Models.OmisionMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instancia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoOmision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OmisionesMarca");
                });

            modelBuilder.Entity("SistemaPermisos.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadLecciones")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraSalida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JornadaCompleta")
                        .HasColumnType("bit");

                    b.Property<bool>("Justificado")
                        .HasColumnType("bit");

                    b.Property<bool>("MediaJornada")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaComprobante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaJustificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConvocatoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMotivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRebajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("SistemaPermisos.Models.ReporteDano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReportesDanos");
                });

            modelBuilder.Entity("SistemaPermisos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "admin@escuela.edu",
                            FechaRegistro = new DateTime(2025, 3, 19, 21, 15, 40, 672, DateTimeKind.Local).AddTicks(9157),
                            Nombre = "Administrador",
                            Password = "$2a$11$DF9hLtS3s5ECR8y.7NUz1udVWKVSQRaY/hr1SE8uiGl4GR4X8Ajx6",
                            Rol = "Admin",
                            UltimaActualizacion = new DateTime(2025, 3, 19, 21, 15, 40, 672, DateTimeKind.Local).AddTicks(9171)
                        },
                        new
                        {
                            Id = 2,
                            Correo = "docente@escuela.edu",
                            FechaRegistro = new DateTime(2025, 3, 19, 21, 15, 40, 803, DateTimeKind.Local).AddTicks(6072),
                            Nombre = "Docente Demo",
                            Password = "$2a$11$QmBv.613fktvR/r0.Fp4MeTpj7iE52UONo41KP63ODv/a6NOkPeoq",
                            Rol = "Docente",
                            UltimaActualizacion = new DateTime(2025, 3, 19, 21, 15, 40, 803, DateTimeKind.Local).AddTicks(6088)
                        });
                });

            modelBuilder.Entity("SistemaPermisos.Models.OmisionMarca", b =>
                {
                    b.HasOne("SistemaPermisos.Models.Usuario", "Usuario")
                        .WithMany("OmisionesMarca")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPermisos.Models.Permiso", b =>
                {
                    b.HasOne("SistemaPermisos.Models.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPermisos.Models.ReporteDano", b =>
                {
                    b.HasOne("SistemaPermisos.Models.Usuario", "Usuario")
                        .WithMany("ReportesDanos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPermisos.Models.Usuario", b =>
                {
                    b.Navigation("OmisionesMarca");

                    b.Navigation("Permisos");

                    b.Navigation("ReportesDanos");
                });
#pragma warning restore 612, 618
        }
    }
}
